const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.user = require("./user.model");
db.role = require("./role.model");
db.userProfile = require('./userProfile.model');
db.ROLES = ["user", "admin", "moderator"];
db.purchases = require("./purchases.model");
db.product = require("./product.model");
db.business = require ("./business.model");
db.notification = require ("./notification.model");
db.inventory = require ("./inventory.model");
db.payment = require ("./payment.model")
db.customer = require ("./customer.model")
db.category = require ("./category.model")
db.order_item = require ("./order_item.model")
db.order = require ("./order.model")
module.exports = db;